name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */12 * * *'   # runs every 12 hours
  workflow_dispatch:          # lets you run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Kshitiz-kothari31/Adven_Tour.git
          git fetch upstream

      - name: Merge upstream into main
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Aman17123/Adven_Tour.git main
